name: CI

on:
  push:
    branches:
      - master
  pull_request: ~

env:
  # Increment this to invalidate the cache without modifying requirements.txt
  PIPCACHEVERSION: 0

jobs:
  pylint:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v2
      - name: Set up Python
        id: setup-python
        uses: actions/setup-python@v2
        with:
          # qutip does not support 3.10 yet
          python-version: '3.9.x'
      - name: Set up cache
        id: cache
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-${{ steps.setup-python.outputs.python-version }}-${{ hashFiles('requirements.txt') }}-${{ env.PIPCACHEVERSION }}
          restore-keys: |
            ${{ runner.os }}-${{ steps.setup-python.outputs.python-version }}-${{ hashFiles('requirements.txt') }}-
            ${{ runner.os }}-${{ steps.setup-python.outputs.python-version }}-
      - name: Install package and pylint
        run: python -m pip install . pylint
      - name: Run pylint
        run: pylint --errors-only --jobs=0 pyEPR
